<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="MAIN" Id="{3163ddc5-cc52-4a07-903d-877f782f00da}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	TheThing	: FB_TheThing;
	OtherThing	: FB_OtherThing;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[thething();
IF theThing.prepare_to_do_the_thing() THEN
	IF theThing.do_the_thing() THEN
		OtherThing.DoSomething();
	END_IF
END_IF

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="2" />
      <LineId Id="16" Count="1" />
      <LineId Id="2" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>