<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="MAIN" Id="{8a9b52c3-21a9-4800-996e-a0c3716d80ae}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	mErrACK AT %Q*	: BOOL;
	mRun AT %Q*		: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[mRun := True;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>